version: '3'

services:

  nginx:
    container_name: punzh_nginx
    restart: "on-failure"
    image: nginx:latest
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./images/nginx/punzh.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./app:/app/
    depends_on:
      - django
    networks:
      - punzh-net

  django:
    #tty: true
    restart: "on-failure"
    container_name: punzh_django
    volumes:
      - ./app:/app
    build:
      context: ./
      dockerfile: images/django/Dockerfile
    depends_on:
      - db
    command: uwsgi --ini /app/uwsgi.ini
    expose:
      - "3000"
    networks:
      - punzh-net

  db:
    container_name: punzh_db
    image: postgres
    restart: "on-failure"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=punzh_dict
    networks:
      - punzh-net

  pgadmin:
    container_name: punzh_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=fedoto4kin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD:-12345}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    networks:
      - punzh-net
    depends_on:
      - "db"


networks:
  punzh-net:
    driver: bridge
